/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MembersRouteImport } from './routes/members'
import { Route as FormsRouteImport } from './routes/forms'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DepartmentsIndexRouteImport } from './routes/departments.index'
import { Route as FShareIdRouteImport } from './routes/f.$shareId'
import { Route as DepartmentsIdRouteImport } from './routes/departments.$id'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsRoute = FormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsIndexRoute = DepartmentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DepartmentsRoute,
} as any)
const FShareIdRoute = FShareIdRouteImport.update({
  id: '/f/$shareId',
  path: '/f/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsIdRoute = DepartmentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DepartmentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/departments': typeof DepartmentsRouteWithChildren
  '/events': typeof EventsRoute
  '/finance': typeof FinanceRoute
  '/forms': typeof FormsRoute
  '/members': typeof MembersRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/departments/$id': typeof DepartmentsIdRoute
  '/f/$shareId': typeof FShareIdRoute
  '/departments/': typeof DepartmentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/events': typeof EventsRoute
  '/finance': typeof FinanceRoute
  '/forms': typeof FormsRoute
  '/members': typeof MembersRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/departments/$id': typeof DepartmentsIdRoute
  '/f/$shareId': typeof FShareIdRoute
  '/departments': typeof DepartmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/departments': typeof DepartmentsRouteWithChildren
  '/events': typeof EventsRoute
  '/finance': typeof FinanceRoute
  '/forms': typeof FormsRoute
  '/members': typeof MembersRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/departments/$id': typeof DepartmentsIdRoute
  '/f/$shareId': typeof FShareIdRoute
  '/departments/': typeof DepartmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attendance'
    | '/departments'
    | '/events'
    | '/finance'
    | '/forms'
    | '/members'
    | '/settings'
    | '/signin'
    | '/departments/$id'
    | '/f/$shareId'
    | '/departments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attendance'
    | '/events'
    | '/finance'
    | '/forms'
    | '/members'
    | '/settings'
    | '/signin'
    | '/departments/$id'
    | '/f/$shareId'
    | '/departments'
  id:
    | '__root__'
    | '/'
    | '/attendance'
    | '/departments'
    | '/events'
    | '/finance'
    | '/forms'
    | '/members'
    | '/settings'
    | '/signin'
    | '/departments/$id'
    | '/f/$shareId'
    | '/departments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttendanceRoute: typeof AttendanceRoute
  DepartmentsRoute: typeof DepartmentsRouteWithChildren
  EventsRoute: typeof EventsRoute
  FinanceRoute: typeof FinanceRoute
  FormsRoute: typeof FormsRoute
  MembersRoute: typeof MembersRoute
  SettingsRoute: typeof SettingsRoute
  SigninRoute: typeof SigninRoute
  FShareIdRoute: typeof FShareIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms': {
      id: '/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof FormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments/': {
      id: '/departments/'
      path: '/'
      fullPath: '/departments/'
      preLoaderRoute: typeof DepartmentsIndexRouteImport
      parentRoute: typeof DepartmentsRoute
    }
    '/f/$shareId': {
      id: '/f/$shareId'
      path: '/f/$shareId'
      fullPath: '/f/$shareId'
      preLoaderRoute: typeof FShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments/$id': {
      id: '/departments/$id'
      path: '/$id'
      fullPath: '/departments/$id'
      preLoaderRoute: typeof DepartmentsIdRouteImport
      parentRoute: typeof DepartmentsRoute
    }
  }
}

interface DepartmentsRouteChildren {
  DepartmentsIdRoute: typeof DepartmentsIdRoute
  DepartmentsIndexRoute: typeof DepartmentsIndexRoute
}

const DepartmentsRouteChildren: DepartmentsRouteChildren = {
  DepartmentsIdRoute: DepartmentsIdRoute,
  DepartmentsIndexRoute: DepartmentsIndexRoute,
}

const DepartmentsRouteWithChildren = DepartmentsRoute._addFileChildren(
  DepartmentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttendanceRoute: AttendanceRoute,
  DepartmentsRoute: DepartmentsRouteWithChildren,
  EventsRoute: EventsRoute,
  FinanceRoute: FinanceRoute,
  FormsRoute: FormsRoute,
  MembersRoute: MembersRoute,
  SettingsRoute: SettingsRoute,
  SigninRoute: SigninRoute,
  FShareIdRoute: FShareIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
